/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                foreground: "var(--foreground-color)" /* Gray 700 - Gray 100 */,
                background: "var(--background-color)" /* Gray 100 - Gray 700 */,
                primary_1: "var(--primary-color-1)" /* Purple 400 - Purple 900 */,
                primary_2: "var(--primary-color-2)" /* Purple 900 - Purple 400 */,
                primary_3: "var(--primary-color-3)" /* Purple 500 - Purple 700 */,
                primary_4: "var(--primary-color-4)" /* Purple 700 - Purple 500 */,
                secondary_1: "var(--secondary-color-1)" /* Gray 400 - Gray 900 */,
                secondary_2: "var(--secondary-color-2)" /* Gray 900 - Gray 400 */,
            },
            fontSize: {
                sme: ["0.875em", "1.25em"],
                mde: ["1em", "1.5em"],
                lge: ["1.125em", "1.75em"],
                xle: ["1.25em", "1.75em"],
                "2xle": ["1.5em", "2em"],
            },
            borderWidth: {
                "0.5e": "0.05em",
                "1e": "0.1em",
                "1.5e": "0.15em",
                "2e": "0.2em",
                "2.5e": "0.25em",
                "3e": "0.3em",
                "3.5e": "0.35em",
                "4e": "0.4em",
                "4.5e": "0.45em",
                "5e": "0.5em",
            },
            spacing: {
                "0.5e": "0.125em",
                "1e": "0.25em",
                "1.5e": "0.375em",
                "2e": "0.5em",
                "2.5e": "0.625em",
                "3e": "0.75em",
                "3.5e": "0.875em",
                "4e": "1em",
                "5e": "1.25em",
                "6e": "1.5em",
                "7e": "1.75em",
                "8e": "2em",
                "9e": "2.25em",
                "10e": "2.5em",
                "11e": "2.75em",
                "12e": "3em",
                "14e": "3.5em",
                "16e": "4em",
                "20e": "5em",
                "24e": "6em",
                "28e": "7em",
                "32e": "8em",
                "36e": "9em",
                "40e": "10em",
                "44e": "11em",
                "48e": "12em",
                "52e": "13em",
                "56e": "14em",
                "60e": "15em",
                "64e": "16em",
                "72e": "18em",
                "80e": "20em",
                "96e": "24em",
            },
        },
    },
    plugins: [],
};
